[package]
name = "pcp"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
swayipc = "3"

[[bin]]
name = "daemon"
path = "src/daemon.rs"

[[bin]]
name = "client"
path = "src/client/main.rs"
